### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by jaffa4** [creswick/chatter#31]
Hello,
I am trying to use your package... on Windows
I get this 

stack install chatter

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for chatter-0.9.1.0:
   cereal-0.5.4.0 must match >=0.4.0.1 && <0.5.4.0 (latest applicable is 0.5.3.0)
needed for unknown reason - stack invariant violated.
What is this?

**Comment by creswick** [comment]
I'm not very familiar with stack, but I was able to get it to install by updating my global stack.yaml, adding three lines to the extra-deps: setting.

Note that the path to your global-project/stack.yaml will be different; I don't have a windows machine.  The error you saw should direct you to this file, though.
```yaml
$HOME/.stack/global-project/stack.yaml
# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/Users/exc20816/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
flags: {}
extra-package-dbs: []
packages: []
extra-deps:
- fullstop-0.1.4
- tokenize-0.3.0
- cereal-0.5.3.0
resolver: lts-8.2
```

Maybe someone else can help figure out the "right" way to fix this; editing a global config doesn't seem right.
